FROM alpine:3.15

RUN apk add --no-cache  -q cmake --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
&& apk add --no-cache  -q \
    gcc \
    g++ \
    make \
    bzip2-dev \
    libbz2 \
    zstd-dev \
    libdwarf \
    libdwarf-dev \
    binutils \
    binutils-dev \
    libunwind-dev \
    libgcc \
    gcc-objc \
    musl \
    musl-dev \
    libstdc++ \
    elfutils-dev \
    openssl-dev \
    clang-extra-tools \
    libexecinfo-dev \
    numactl-dev \
    numactl-tools \
    mbedtls-dev \
    git \
    wget \
    python3 \
    py3-pip \
    libsodium-dev \
    tar \
    p7zip \
    libbsd-dev \
    doxygen \
    graphviz \
    openjdk8 \
    # https://github.com/akapril/alpine-opencv-java/blob/master/Dockerfile if full integration is needed
    opencv \
    opencv-dev