#Location of query set
# For each query set we will run the experiments
QuerySetLocation: ''
# LOG level
LogLevel: LOG_ERROR
# Sleep interval between each run
StartupSleepIntervalInSeconds: 3
# Number of times experiment is to be repeated
NumOfRuns: 3

RunConfig:
  - QueryPlacementStrategy: TopDown
    IncrementalPlacement: true
  - QueryPlacementStrategy: TopDown
    IncrementalPlacement: false
#  - QueryPlacementStrategy: ILP
#    IncrementalPlacement: true
#  - QueryPlacementStrategy: ILP
#    IncrementalPlacement: false

