# CPACK will work but we can't install this on alpine itself, disabled for now
FROM nebulastream/nes-build-image:alpine AS buildimg

COPY ./ /nebulastream

RUN mkdir -p /nebulastream/build && \
  cd /nebulastream/build && \
  cmake -DCMAKE_BUILD_TYPE=Release -DNES_SELF_HOSTING=1 -DNES_USE_OPC=0 -DNES_USE_MQTT=1 -DNES_USE_ADAPTIVE=0 .. && \
  make version && make -j4

FROM alpine:3.15 AS execimg
RUN apk add --no-cache --no-progress -q \
    g++ \
    gcc-objc \
    libstdc++6 \
    libgcc \
    libc6-compat \
    musl \
    musl-dev \
    numactl-dev \
    binutils \
    binutils-dev \
    libunwind-dev \
    libdwarf \
    libdwarf-dev \
    elfutils-dev