FROM ubuntu:22.04 AS execimg
ARG TARGETARCH
COPY ./nes-$TARGETARCH.deb nes.deb

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq  \
    libstdc++-9-dev \
    libobjc-9-dev \
    libstdc++6  \
    libgcc-s1 \
    libc6  \
    libc6-dev \
    binutils  \
    libnuma-dev  \
    libdwarf-dev  \
    libdwarf1 \
    libomp-12-dev \
    binutils-dev \
    libunwind-dev  \
    libdw-dev iproute2  \
    ifupdown  \
    net-tools --no-install-recommends -y -qq && DEBIAN_FRONTEND="noninteractive" apt install -qq  ./nes.deb &&  rm nes.deb

COPY ./docker/executableImage/entrypoint-nes-executable.sh /entrypoint.sh

ENV coordinatorCLIConf="--coordinatorIp=127.0.0.1 --rpcPort=12346 --restIp=0.0.0.0 --restPort=8081 --logLevel=LOG_INFO"
ENV workerCLIConf="--coordinatorPort=12346 --logLevel=LOG_INFO --physicalSources.type=CSVSource --physicalSources.filePath=/opt/local/nebula-stream/exdra.csv --physicalSources.numberOfBuffersToProduce=100 --physicalSources.sourceGatheringInterval=1 --physicalSources.physicalSourceName=exdra_worker_1 --physicalSources.logicalSourceName=exdra --physicalSources.skipHeader=false --physicalSources.delimiter=,"

ENTRYPOINT ["/entrypoint.sh"]
